In [1]:
import yfinance as yf
import pandas as pd
import sqlite3
from datetime import datetime

In [2]:
import sys
sys.path.insert(0, '..')
from src.config import (TICKERS as CORE_TICKERS, BENCHMARKS,
                        START_DATE, END_DATE, get_hf_universe)

# Extend the curated 57-name universe with every ticker that has an
# ingested HF transcript (run 02b_ingest_hf_transcripts.ipynb first to
# unlock the full ~685-name universe).
USE_HF_UNIVERSE = True
hf_universe = get_hf_universe('../data/market.db') if USE_HF_UNIVERSE else []
TICKERS = sorted(set(CORE_TICKERS) | set(hf_universe))
ALL_SYMBOLS = TICKERS + BENCHMARKS
print(f'Universe: {len(TICKERS)} tickers + {len(BENCHMARKS)} benchmarks '
      f'({len(hf_universe)} from HF transcript ingest)')

Universe: 695 tickers + 3 benchmarks (685 from HF transcript ingest)

In [3]:
# Chunked download — one giant yf.download() call on ~700 symbols is
# fragile (a single bad symbol can poison the whole request) and spikes
# memory. 100-symbol chunks keep each request fast and retryable.
CHUNK = 100
frames = []
for i in range(0, len(ALL_SYMBOLS), CHUNK):
    syms = ALL_SYMBOLS[i:i + CHUNK]
    d = yf.download(syms, start=START_DATE, end=END_DATE,
                    auto_adjust=True, progress=False, threads=True)
    frames.append(d)
    print(f'  chunk {i // CHUNK + 1}/{-(-len(ALL_SYMBOLS) // CHUNK)}: '
          f'{len(syms)} symbols, {d.shape[0]} days')

data = pd.concat(frames, axis=1) if len(frames) > 1 else frames[0]
print(f"Shape: {data.shape[0]} rows (trading days) x {data.shape[1]} columns")

$AT: possibly delisted; no timezone found

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AMBC"}}}

$AMBC: possibly delisted; no timezone found

$ATGE: possibly delisted; no timezone found

$AKS: possibly delisted; no timezone found

$ATVI: possibly delisted; no timezone found

$ABMD: possibly delisted; no timezone found

$BF.B: possibly delisted; no price data found  (1d 2016-07-01 -> 2026-06-25)

$ALXN: possibly delisted; no timezone found

$BIG: possibly delisted; no timezone found

$ALTR: possibly delisted; no timezone found

$ADS: possibly delisted; no timezone found

$ANSS: possibly delisted; no timezone found

12 Failed downloads:

['AT', 'AMBC', 'ATGE', 'AKS', 'ATVI', 'ABMD', 'ALXN', 'BIG', 'ALTR', 'ADS', 'ANSS']: possibly delisted; no timezone found

['BF.B']: possibly delisted; no price data found  (1d 2016-07-01 -> 2026-06-25)

  chunk 1/7: 100 symbols, 2508 days

$DO: possibly delisted; no timezone found

$CBH: possibly delisted; no timezone found

$DRE: possibly delisted; no timezone found

$DNB: possibly delisted; no timezone found

$DAY: possibly delisted; no timezone found

$CTLT: possibly delisted; no timezone found

$DFS: possibly delisted; no timezone found

$DISCK: possibly delisted; no timezone found

$DISH: possibly delisted; no timezone found

$CXO: possibly delisted; no timezone found

$COOP: possibly delisted; no timezone found

$CIT: possibly delisted; no timezone found

$CERN: possibly delisted; no timezone found

$CMA: possibly delisted; no timezone found

$CTRA: possibly delisted; no price data found  (1d 2016-07-01 -> 2026-06-25)

15 Failed downloads:

['DO', 'CBH', 'DRE', 'DNB', 'DAY', 'CTLT', 'DFS', 'DISCK', 'DISH', 'CXO', 'COOP', 'CIT', 'CERN', 'CMA']: possibly delisted; no timezone found

['CTRA']: possibly delisted; no price data found  (1d 2016-07-01 -> 2026-06-25)

  chunk 2/7: 100 symbols, 2508 days

$FL: possibly delisted; no timezone found

$FRC: possibly delisted; no timezone found

$HES: possibly delisted; no timezone found

$HBI: possibly delisted; no timezone found

$FI: possibly delisted; no timezone found

$ETFC: possibly delisted; no timezone found

$FLIR: possibly delisted; no timezone found

$HFC: possibly delisted; no timezone found

$ENDP: possibly delisted; no timezone found

$HOLX: possibly delisted; no timezone found

10 Failed downloads:

['FL', 'FRC', 'HES', 'HBI', 'FI', 'ETFC', 'FLIR', 'HFC', 'ENDP', 'HOLX']: possibly delisted; no timezone found

  chunk 3/7: 100 symbols, 2508 days

$IGT: possibly delisted; no timezone found

$JWN: possibly delisted; no timezone found

$LM: possibly delisted; no timezone found

$LSI: possibly delisted; no timezone found

$KSU: possibly delisted; no timezone found

$IPG: possibly delisted; no timezone found

$JNPR: possibly delisted; no timezone found

$K: possibly delisted; no timezone found

8 Failed downloads:

['IGT', 'JWN', 'LM', 'LSI', 'KSU', 'IPG', 'JNPR', 'K']: possibly delisted; no timezone found

  chunk 4/7: 100 symbols, 2508 days

$NLSN: possibly delisted; no timezone found

$MRO: possibly delisted; no timezone found

$ODP: possibly delisted; no timezone found

$PARA: possibly delisted; no timezone found

$PBCT: possibly delisted; no timezone found

$PDCO: possibly delisted; no timezone found

$MMC: possibly delisted; no timezone found

$MXIM: possibly delisted; no timezone found

$MNK: possibly delisted; no timezone found

$PLL: possibly delisted; no timezone found

$MDP: possibly delisted; no timezone found

$NBL: possibly delisted; no timezone found

12 Failed downloads:

['NLSN', 'MRO', 'ODP', 'PARA', 'PBCT', 'PDCO', 'MMC', 'MXIM', 'MNK', 'PLL', 'MDP', 'NBL']: possibly delisted; no timezone found

  chunk 5/7: 100 symbols, 2508 days

$SNV: possibly delisted; no timezone found

$RRD: possibly delisted; no timezone found

$QEP: possibly delisted; no timezone found

$SQ: possibly delisted; no timezone found

$TIF: possibly delisted; no timezone found

$SIVB: possibly delisted; no timezone found

$PXD: possibly delisted; no timezone found

$TGNA: possibly delisted; no timezone found

$SEE: possibly delisted; no timezone found

$SRCL: possibly delisted; no timezone found

10 Failed downloads:

['SNV', 'RRD', 'QEP', 'SQ', 'TIF', 'SIVB', 'PXD', 'TGNA', 'SEE', 'SRCL']: possibly delisted; no timezone found

  chunk 6/7: 100 symbols, 2508 days

$WCG: possibly delisted; no timezone found

$VAR: possibly delisted; no timezone found

$WPX: possibly delisted; no timezone found

$WBA: possibly delisted; no timezone found

$WYND: possibly delisted; no timezone found

$X: possibly delisted; no timezone found

$TSS: possibly delisted; no timezone found

$WRK: possibly delisted; no timezone found

$XLNX: possibly delisted; no timezone found

$TWTR: possibly delisted; no timezone found

$XEC: possibly delisted; no timezone found

$VIAB: possibly delisted; no timezone found

12 Failed downloads:

['WCG', 'VAR', 'WPX', 'WBA', 'WYND', 'X', 'TSS', 'WRK', 'XLNX', 'TWTR', 'XEC', 'VIAB']: possibly delisted; no timezone found

  chunk 7/7: 98 symbols, 2508 days
Shape: 2508 rows (trading days) x 3569 columns

In [4]:
data.head()

Price      Adj Close                                            ...    Volume  \
Ticker          ABMD ADS AKS ALTR ALXN AMBC ANSS  AT ATGE ATVI  ...       XOM
2016-07-01       NaN NaN NaN  NaN  NaN  NaN  NaN NaN  NaN  NaN  ...   9946300
2016-07-05       NaN NaN NaN  NaN  NaN  NaN  NaN NaN  NaN  NaN  ...  10744100
2016-07-06       NaN NaN NaN  NaN  NaN  NaN  NaN NaN  NaN  NaN  ...  13144400
2016-07-07       NaN NaN NaN  NaN  NaN  NaN  NaN NaN  NaN  NaN  ...  12240700
2016-07-08       NaN NaN NaN  NaN  NaN  NaN  NaN NaN  NaN  NaN  ...   9807600

Price                                                                          \
Ticker         XRAY      XRX      XYL      YUM      ZBH     ZBRA     ZION  ZM
2016-07-01  1370700  1968277  1199100  2548173   889199   757900  4301700 NaN
2016-07-05  1394900  1686991  1519300  3534670  1225082   994500  7121700 NaN
2016-07-06  1630400  1861599  1487000  4323089  1892934  1239900  5310900 NaN
2016-07-07  1156500  1784485  1499400  4921497  1528108  1104400  4741400 NaN
2016-07-08  1428200  1746231  1109100  5619918  1411512   743700  4748900 NaN

Price
Ticker          ZTS
2016-07-01  2008300
2016-07-05  2655400
2016-07-06  3451600
2016-07-07  2338000
2016-07-08  2852000

[5 rows x 3569 columns]

In [5]:
data['Close'].head()

Ticker,A,AA,AAL,AAP,AAPL,ABBV,ABMD,ABNB,ABT,ACGL,...,XOM,XRAY,XRX,XYL,YUM,ZBH,ZBRA,ZION,ZM,ZTS
2016-07-01,41.233749,21.700464,28.186813,143.369858,21.829321,41.530743,NaN,NaN,32.786671,22.669420,...,60.797935,54.009125,12.932576,39.708168,49.963726,107.904831,49.820000,18.745232,NaN,43.770042
2016-07-05,40.447910,21.041500,27.802406,140.630371,21.624439,41.007549,NaN,NaN,32.703754,22.472902,...,60.266666,53.853153,12.780427,39.681622,49.670631,107.252129,47.610001,17.631952,NaN,43.816151
2016-07-06,41.113564,20.882439,27.245010,140.857162,21.747362,41.967842,NaN,NaN,33.856331,22.425356,...,60.959911,54.364403,12.891084,40.336487,50.346550,108.888405,46.930000,18.045670,NaN,44.360401
2016-07-07,41.067337,21.223280,28.254086,140.578018,21.840706,42.007584,NaN,NaN,34.295822,22.374643,...,60.227791,54.156433,12.974072,40.380733,50.430283,109.103027,46.990002,18.361599,NaN,43.991432
2016-07-08,42.047340,22.313986,28.869141,143.823517,22.009169,42.491032,NaN,NaN,34.735294,22.431696,...,60.603596,54.927620,13.195376,41.071014,51.297615,111.669174,47.880001,18.609835,NaN,44.738602

In [6]:
print("Missing Close prices per ticker:")
print(data['Close'].isna().sum())

Missing Close prices per ticker:
Ticker
A         0
AA        0
AAL       0
AAP       0
AAPL      0
       ...
ZBH       0
ZBRA      0
ZION      0
ZM      703
ZTS       0
Length: 698, dtype: int64

In [7]:
long_data = data.stack(level='Ticker', future_stack=True).reset_index()
long_data.columns = [c.lower() for c in long_data.columns]
long_data = long_data.rename(columns={'level_0': 'date'})
print(f"Shape: {long_data.shape}")
long_data.head(10)

Shape: (1750584, 8)

        date ticker  adj close  close  high  low  open  volume
0 2016-07-01   ABMD        NaN    NaN   NaN  NaN   NaN     NaN
1 2016-07-01    ADS        NaN    NaN   NaN  NaN   NaN     NaN
2 2016-07-01    AKS        NaN    NaN   NaN  NaN   NaN     NaN
3 2016-07-01   ALTR        NaN    NaN   NaN  NaN   NaN     NaN
4 2016-07-01   ALXN        NaN    NaN   NaN  NaN   NaN     NaN
5 2016-07-01   AMBC        NaN    NaN   NaN  NaN   NaN     NaN
6 2016-07-01   ANSS        NaN    NaN   NaN  NaN   NaN     NaN
7 2016-07-01     AT        NaN    NaN   NaN  NaN   NaN     NaN
8 2016-07-01   ATGE        NaN    NaN   NaN  NaN   NaN     NaN
9 2016-07-01   ATVI        NaN    NaN   NaN  NaN   NaN     NaN

In [8]:
import sqlite3
DB_PATH = "../data/market.db"
conn = sqlite3.connect(DB_PATH)
long_data.to_sql('prices', conn, if_exists='replace', index=False)
result = conn.execute("SELECT COUNT(*) FROM prices").fetchone()
print(f"Saved {result[0]} rows to the 'prices' table in {DB_PATH}")
conn.close()
print("Database connection closed.")

Saved 1750584 rows to the 'prices' table in ../data/market.db
Database connection closed.

In [9]:
import time
earnings_frames = []
failed = []
t0 = time.time()
for i, ticker in enumerate(TICKERS):
    try:
        t = yf.Ticker(ticker)
        ed = t.get_earnings_dates(limit=60)
        if ed is not None and len(ed) > 0:
            ed = ed.reset_index()
            ed['ticker'] = ticker
            earnings_frames.append(ed)
        else:
            failed.append(ticker)
    except Exception as e:
        failed.append(ticker)
        print(f"{ticker}: ERROR - {e}")
    if (i + 1) % 25 == 0:
        el = time.time() - t0
        print(f'  [{i+1}/{len(TICKERS)}] {el:.0f}s elapsed, '
              f'~{el / (i+1) * (len(TICKERS)-i-1) / 60:.0f} min left')
    time.sleep(0.5)  # stay under Yahoo rate limits without doubling runtime
print(f"\nCollected earnings data for {len(earnings_frames)}/{len(TICKERS)} companies "
      f"in {(time.time()-t0)/60:.1f} min")
if failed:
    print(f"No data: {failed}")

ABMD: No earnings dates found, symbol may be delisted

ADS: No earnings dates found, symbol may be delisted

  [25/695] 27s elapsed, ~12 min left

AKS: No earnings dates found, symbol may be delisted

ALXN: No earnings dates found, symbol may be delisted

  [50/695] 56s elapsed, ~12 min left

AT: No earnings dates found, symbol may be delisted

ATVI: No earnings dates found, symbol may be delisted

  [75/695] 82s elapsed, ~11 min left

BF.B: No earnings dates found, symbol may be delisted

BIG: No earnings dates found, symbol may be delisted

  [100/695] 109s elapsed, ~11 min left

CBH: No earnings dates found, symbol may be delisted

CERN: No earnings dates found, symbol may be delisted

CHIR: No earnings dates found, symbol may be delisted

  [125/695] 136s elapsed, ~10 min left

CIT: No earnings dates found, symbol may be delisted

  [150/695] 164s elapsed, ~10 min left

CXO: No earnings dates found, symbol may be delisted

  [175/695] 190s elapsed, ~9 min left

DISCK: No earnings dates found, symbol may be delisted

DISH: No earnings dates found, symbol may be delisted

DO: No earnings dates found, symbol may be delisted

DRE: No earnings dates found, symbol may be delisted

  [200/695] 217s elapsed, ~9 min left

ENDP: No earnings dates found, symbol may be delisted

  [225/695] 245s elapsed, ~9 min left

ETFC: No earnings dates found, symbol may be delisted

  [250/695] 273s elapsed, ~8 min left

FLIR: No earnings dates found, symbol may be delisted

FRC: No earnings dates found, symbol may be delisted

  [275/695] 300s elapsed, ~8 min left

HFC: No earnings dates found, symbol may be delisted

HOLX: No earnings dates found, symbol may be delisted

  [300/695] 328s elapsed, ~7 min left

INFO: No earnings dates found, symbol may be delisted

  [325/695] 356s elapsed, ~7 min left

  [350/695] 383s elapsed, ~6 min left

KSU: No earnings dates found, symbol may be delisted

LM: No earnings dates found, symbol may be delisted

  [375/695] 410s elapsed, ~6 min left

LSI: No earnings dates found, symbol may be delisted

  [400/695] 437s elapsed, ~5 min left

MDP: No earnings dates found, symbol may be delisted

MNK: No earnings dates found, symbol may be delisted

  [425/695] 464s elapsed, ~5 min left

MXIM: No earnings dates found, symbol may be delisted

NBL: No earnings dates found, symbol may be delisted

NLSN: No earnings dates found, symbol may be delisted

  [450/695] 491s elapsed, ~4 min left

  [475/695] 520s elapsed, ~4 min left

PBCT: No earnings dates found, symbol may be delisted

  [500/695] 547s elapsed, ~4 min left

POM: No earnings dates found, symbol may be delisted

PXD: No earnings dates found, symbol may be delisted

QEP: No earnings dates found, symbol may be delisted

  [525/695] 575s elapsed, ~3 min left

RRD: No earnings dates found, symbol may be delisted

SAF: No earnings dates found, symbol may be delisted

SEE: No earnings dates found, symbol may be delisted

  [550/695] 601s elapsed, ~3 min left

SIVB: No earnings dates found, symbol may be delisted

STI: No earnings dates found, symbol may be delisted

  [575/695] 628s elapsed, ~2 min left

TIF: No earnings dates found, symbol may be delisted

  [600/695] 655s elapsed, ~2 min left

TSS: No earnings dates found, symbol may be delisted

TWTR: No earnings dates found, symbol may be delisted

  [625/695] 682s elapsed, ~1 min left

UST: No earnings dates found, symbol may be delisted

VAR: No earnings dates found, symbol may be delisted

VIAB: No earnings dates found, symbol may be delisted

  [650/695] 708s elapsed, ~1 min left

WCG: No earnings dates found, symbol may be delisted

WPX: No earnings dates found, symbol may be delisted

WRK: No earnings dates found, symbol may be delisted

  [675/695] 736s elapsed, ~0 min left

WYND: No earnings dates found, symbol may be delisted

XEC: No earnings dates found, symbol may be delisted

XLNX: No earnings dates found, symbol may be delisted

Collected earnings data for 642/695 companies in 12.6 min
No data: ['ABMD', 'ADS', 'AKS', 'ALXN', 'AT', 'ATVI', 'BF.B', 'BIG', 'CBH', 'CERN', 'CHIR', 'CIT', 'CXO', 'DISCK', 'DISH', 'DO', 'DRE', 'ENDP', 'ETFC', 'FLIR', 'FRC', 'HFC', 'HOLX', 'INFO', 'KSU', 'LM', 'LSI', 'MDP', 'MNK', 'MXIM', 'NBL', 'NLSN', 'PBCT', 'POM', 'PXD', 'QEP', 'RRD', 'SAF', 'SEE', 'SIVB', 'STI', 'TIF', 'TSS', 'TWTR', 'UST', 'VAR', 'VIAB', 'WCG', 'WPX', 'WRK', 'WYND', 'XEC', 'XLNX']

In [10]:
earnings_df = pd.concat(earnings_frames, ignore_index=True)
earnings_df.columns = [c.lower().replace(' ', '_') for c in earnings_df.columns]
print(f"Total rows: {len(earnings_df)}")
print(f"Columns: {earnings_df.columns.tolist()}")
earnings_df.head(10)

Total rows: 55080
Columns: ['earnings_date', 'eps_estimate', 'reported_eps', 'surprise(%)', 'ticker']

              earnings_date  eps_estimate  reported_eps  surprise(%) ticker
0 2026-08-26 16:00:00-04:00          1.49           NaN          NaN      A
1 2026-05-27 16:00:00-04:00          1.41          1.49         5.80      A
2 2026-02-25 16:00:00-05:00          1.37          1.36        -0.60      A
3 2025-11-24 16:00:00-05:00          1.58          1.59         0.37      A
4 2025-08-27 16:00:00-04:00          1.37          1.37         0.17      A
5 2025-05-28 16:00:00-04:00          1.26          1.31         3.62      A
6 2025-02-26 16:00:00-05:00          1.27          1.31         2.99      A
7 2024-11-25 16:00:00-05:00          1.41          1.46         3.90      A
8 2024-08-21 16:00:00-04:00          1.26          1.32         4.93      A
9 2024-05-29 16:00:00-04:00          1.19          1.22         2.42      A

In [11]:
earnings_df = earnings_df.rename(columns={'surprise(%)': 'eps_surprise_pct'})
earnings_df['earnings_date'] = pd.to_datetime(earnings_df['earnings_date'], utc=True).dt.tz_localize(None).dt.normalize()
earnings_df = earnings_df[earnings_df['earnings_date'] >= '2016-07-01']
print(f"Rows after filtering to mid-2016+: {len(earnings_df)}")

Rows after filtering to mid-2016+: 25116

In [12]:
conn = sqlite3.connect("../data/market.db")
earnings_df.to_sql('earnings', conn, if_exists='replace', index=False)
count = conn.execute("SELECT COUNT(*) FROM earnings").fetchone()[0]
print(f"Saved {count} rows to 'earnings' table")
conn.close()

Saved 25116 rows to 'earnings' table

In [13]:
import yfinance as yf
vix_raw = yf.download('^VIX', start=START_DATE, end=END_DATE,
                      auto_adjust=True, progress=False)
vix_df = vix_raw['Close'].reset_index()
vix_df.columns = ['date', 'vix_close']
vix_df['date'] = pd.to_datetime(vix_df['date'])
print(f"Pulled {len(vix_df)} VIX days "
      f"from {vix_df['date'].min().date()} to {vix_df['date'].max().date()}")

# Persist — 03's pub_date-anchored return fallback reads this table
conn = sqlite3.connect("../data/market.db")
vix_df.to_sql('vix', conn, if_exists='replace', index=False)
conn.close()
print("Saved to 'vix' table")
vix_df.head()

Pulled 2509 VIX days from 2016-07-01 to 2026-06-24
Saved to 'vix' table

        date  vix_close
0 2016-07-01      14.77
1 2016-07-05      15.58
2 2016-07-06      14.96
3 2016-07-07      14.76
4 2016-07-08      13.20

In [14]:
import sqlite3
import numpy as np
import yfinance as yf
from src.config import START_DATE, END_DATE, COVID_START, COVID_END
from src.returns_calc import PriceMatrix, build_event_returns

conn = sqlite3.connect('../data/market.db')
prices_long = pd.read_sql('SELECT date, ticker, close FROM prices', conn,
                          parse_dates=['date'])
earnings_df = pd.read_sql('SELECT * FROM earnings', conn, parse_dates=['earnings_date'])
try:
    vix_df = pd.read_sql('SELECT date, vix_close FROM vix', conn,
                         parse_dates=['date'])
except Exception:
    print('vix table missing — re-pulling ^VIX')
    _vix_raw = yf.download('^VIX', start=START_DATE, end=END_DATE,
                           auto_adjust=True, progress=False)
    vix_df = _vix_raw['Close'].reset_index()
    vix_df.columns = ['date', 'vix_close']
    vix_df['date'] = pd.to_datetime(vix_df['date'])
conn.close()
print(f'Reloaded {len(prices_long):,} price rows, {len(earnings_df):,} earnings events')

# Vectorized return engine (src/returns_calc.py): searchsorted + fancy
# indexing computes all 6 windows for 30k+ events in well under a second.
# Entry = close of first trading day on/after the earnings date.
pm = PriceMatrix.from_long(prices_long)
vix_series = vix_df.set_index('date')['vix_close'].sort_index()

ev = earnings_df.dropna(subset=['reported_eps'])   # only reported quarters
returns_df = build_event_returns(
    pm, ev[['ticker', 'earnings_date']],
    benchmark='SPY', windows=(1, 30, 90),
    vix=vix_series, covid_range=(COVID_START, COVID_END),
)
print(f'Computed SPY-adjusted returns for {len(returns_df):,} earnings events '
      f'({returns_df["is_covid"].sum()} in COVID window, '
      f'{returns_df["vix_close"].notna().sum():,} with VIX matched)')
returns_df.head(10)

Reloaded 1,750,584 price rows, 25,116 earnings events

Computed SPY-adjusted returns for 24,415 earnings events (3225 in COVID window, 24,415 with VIX matched)

,ticker,earnings_date,return_1d,abnormal_1d,return_30d,abnormal_30d,return_90d,abnormal_90d,vix_close,is_covid
1,A,2026-05-27,0.168681,0.163164,NaN,NaN,NaN,NaN,16.290001,False
2,A,2026-02-25,-0.030067,-0.024513,-0.072697,-0.056274,NaN,NaN,17.930000,False
3,A,2025-11-24,0.023437,0.014032,-0.049346,-0.083466,-0.255574,-0.246966,20.520000,False
4,A,2025-08-27,0.052827,0.049285,0.182841,0.142028,0.248300,0.172294,14.850000,False
5,A,2025-05-28,0.021645,0.017698,0.114174,0.049972,0.282406,0.133132,19.309999,False
6,A,2025-02-26,-0.054956,-0.038994,-0.202220,-0.127760,-0.096286,-0.145913,19.100000,False
7,A,2024-11-25,-0.000892,-0.006114,0.024047,0.049295,-0.258793,-0.094985,14.600000,False
8,A,2024-08-21,0.001643,0.009491,0.034217,0.018268,-0.038260,-0.094252,16.270000,False
9,A,2024-05-29,-0.096646,-0.090012,-0.089391,-0.157242,-0.007516,-0.093582,14.280000,False
10,A,2024-02-27,0.033648,0.034969,0.089356,0.072022,-0.045574,-0.147900,13.430000,False

In [15]:
conn = sqlite3.connect("../data/market.db")
returns_df.to_sql('returns', conn, if_exists='replace', index=False)
saved = conn.execute("SELECT COUNT(*) FROM returns").fetchone()[0]
cols  = conn.execute("PRAGMA table_info(returns)").fetchall()
conn.close()
print(f"Saved {saved} rows to 'returns' table")
print("Columns:", [c[1] for c in cols])

Saved 24415 rows to 'returns' table
Columns: ['ticker', 'earnings_date', 'return_1d', 'abnormal_1d', 'return_30d', 'abnormal_30d', 'return_90d', 'abnormal_90d', 'vix_close', 'is_covid']

In [16]:
print("=== Abnormal 1d (SPY-adjusted) ===")
print(returns_df['abnormal_1d'].describe().round(4))
print("\n=== Abnormal 30d (SPY-adjusted) ===")
print(returns_df['abnormal_30d'].describe().round(4))
print("\n=== Abnormal 90d (SPY-adjusted) ===")
print(returns_df['abnormal_90d'].describe().round(4))
print("\n=== VIX distribution (joined to earnings dates) ===")
print(returns_df['vix_close'].describe().round(2))
print("\n=== COVID-window cohort (vs non-COVID) ===")
print(returns_df.groupby('is_covid')['abnormal_1d'].agg(['count','mean','std']).round(4))
print("\n=== By ticker: mean abnormal 1d ===")
print(returns_df.groupby('ticker')['abnormal_1d']
      .agg(['count','mean','std']).round(4).sort_values('mean', ascending=False))

=== Abnormal 1d (SPY-adjusted) ===
count    23233.0000
mean         0.0002
std          0.0539
min         -0.4887
25%         -0.0198
50%         -0.0004
75%          0.0194
max          1.0791
Name: abnormal_1d, dtype: float64

=== Abnormal 30d (SPY-adjusted) ===
count    23161.0000
mean         0.0016
std          0.1246
min         -0.7744
25%         -0.0617
50%         -0.0035
75%          0.0553
max          2.9593
Name: abnormal_30d, dtype: float64

=== Abnormal 90d (SPY-adjusted) ===
count    22457.0000
mean         0.0057
std          0.2588
min         -0.8033
25%         -0.1143
50%         -0.0103
75%          0.0962
max         15.7553
Name: abnormal_90d, dtype: float64

=== VIX distribution (joined to earnings dates) ===
count    24415.00
mean        18.64
std          6.50
min          9.14
25%         14.01
50%         17.21
75%         21.63
max         76.45
Name: vix_close, dtype: float64

=== COVID-window cohort (vs non-COVID) ===
          count    mean     std
is_covid
False     20185  0.0002  0.0544
True       3048  0.0006  0.0503

=== By ticker: mean abnormal 1d ===
        count    mean     std
ticker
LIFE        2  0.1844  0.2004
AXON       40  0.0528  0.1259
ENPH       40  0.0441  0.1692
FOSL       21  0.0425  0.2387
SMCI       37  0.0390  0.1248
...       ...     ...     ...
SQ          0     NaN     NaN
SRCL        0     NaN     NaN
TGNA        0     NaN     NaN
WBA         0     NaN     NaN
X           0     NaN     NaN

[639 rows x 3 columns]

In [17]:
robust_df = returns_df[~returns_df['is_covid']]
print(f"Excluding COVID window: {len(robust_df)} events "
      f"({len(returns_df) - len(robust_df)} dropped)")
print()
print(robust_df['abnormal_1d'].describe().round(4))
print()
print(robust_df.groupby('ticker')['abnormal_1d']
      .agg(['count','mean','std']).round(4).sort_values('mean', ascending=False))

Excluding COVID window: 21190 events (3225 dropped)

count    20185.0000
mean         0.0002
std          0.0544
min         -0.4887
25%         -0.0195
50%         -0.0002
75%          0.0193
max          1.0791
Name: abnormal_1d, dtype: float64

        count    mean     std
ticker
LIFE        2  0.1844  0.2004
AXON       34  0.0526  0.1309
ENPH       35  0.0441  0.1763
PLTR       20  0.0436  0.1346
PODD       34  0.0399  0.0913
...       ...     ...     ...
SQ          0     NaN     NaN
SRCL        0     NaN     NaN
TGNA        0     NaN     NaN
WBA         0     NaN     NaN
X           0     NaN     NaN

[639 rows x 3 columns]